apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: wisecow

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/part-of: accuknox-assessment
  app.kubernetes.io/managed-by: kustomize

images:
  - name: wisecow
    newName: ghcr.io/antcybersec/wisecow
    newTag: latest
